
server:
  port: 8080
spring:
  application:
    name: api-gateway
  config:
    # Inject cloud Config Server URL, fallback to local
    import: optional:configserver:${CONFIG_SERVER_URL:http://localhost:8888}
