server:
  port: 8081
spring:
  datasource:
    # Inject cloud Postgres credentials, fallback to local
    url: ${POSTGRES_URL:jdbc:postgresql://localhost:5432/fitness_user_db}
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:wdvhu6}
  jpa:
    hibernate:
      ddl-auto: update # CRITICAL: Prevents data wipe on cloud restarts
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka/}

